var languages = [];
languages[0] = 'html';
languages[1] = 'css';
languages[2] = 'javascript';
languages[3] = 'react';
languages[4] = 'node';
languages[5] = 'postgres';
console.log(languages);
var firstElement = languages[0];
console.log('The first element of the array is', firstElement);
var thirdElement = languages[2];
console.log('The 3rd element of the array is', thirdElement);
var length = languages.length;
console.log('The length of the array is', length);
var lastElement = languages[languages.length - 1];
console.log('The last element of the array is', lastElement);
